project_id = "jbicfyqhyictnxafzyav"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.refund-order]
verify_jwt = false
